apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls-portainer
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`portainer-dev.n0secure.org`)
    kind: Rule
    services:
    - name: dev-portainer
      port: 9000
