apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls-portainer
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`portainer.n0secure.org`)
    kind: Rule
    services:
    - name: prod-portainer
      port: 9000
